datasource-classname: org.sqlite.JDBC
datasource-url: jdbc:sqlite:WebBuilder.db
datasource-username: admin
datasource-credentials: p455w0rd
admin-email:
admin-credentials:
registration-name:
registration-client-id:
registration-client-secret:
registration-email-field-name: email
registration-email-verified-field-name: email_verified
spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username:
spring.mail.password: 
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
site-name: WMSBio